# BASICS OF NUMPY

## INTRODUCTION


* NumPy is a Python library.

* NumPy is used for working with arrays.

* NumPy is short for "Numerical Python".

* Numpy is used to perform a wide variety of mathematical operations on arrays.

## INSTALLATION OF NUMPY

If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

Install it using this command: <b> pip install numpy. <b>

## Importing NumPy

Once NumPy is installed, import it in your applications by adding the import keyword like : <b> import numpy <b>

In [4]:
import numpy as np

In [49]:
#some basic commands in numpy as shown below

print(np.__version__)                                          #To see which version you have installed

arr = np.array([[[1, 2, 3, 4],
                [5 ,6, 7, 8]],                                  #Creating an array
              
               [[1, 2, 3, 4],
                [5 ,6, 7, 8]]]
              )                            

print(arr.ndim)                                                #To find the number of dimensions of the array

print(arr.shape)                                               #To find shape of your array

print(arr.size)                                                #To find total number of elements in your array

print(arr.dtype)                                               #To find which data type it is

print(arr.itemsize)                                            #Size in bytes of each element

print(type(a))                                                 


1.20.3
3
(2, 2, 4)
16
int32
4
<class 'numpy.ndarray'>


<b> DIFFERENCE BETWEEN 2-D AND 3-D ARRAYS <b>
   
<b>2-D ARRAY<b>
    
   Creating 2-d array with two arrays. For example:
    
   np.array([[1,2,3], [4,5,6]])
    
<b>3-D ARRAY<b>
    
 An array that 2-D array elements is called 3-D ARRAY. For example:
    
 np.array([[[1, 2, 3], [4, 5, 6]],
     [[1, 2, 3], [4, 5, 6]]])
    

### INDEXING (ACCESING ARRAY ELEMENTS)



In [23]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])                                                      #Adding last two elements in an array

arr1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])                                #Since, It is an 2-D array

print('5th element on 2nd row: ', arr1[1, 4])

arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])        #Since, It is an 3-D array

print('3rd element on 2nd row of first 2-d array: ',arr2[0, 1, 2])

arr3 = np.array([[1,2,3,4,5], [6,7,8,9,10]])                                #Negative inedexing will start from back side of array

print('Last element from 2nd dim: ', arr3[1, -1])




7
5th element on 2nd row:  10
3rd element on 2nd row of first 2-d array:  6
Last element from 2nd dim:  10


### CREATIND ARRAYS WITH ZEROS, ONES, EMPTY, NORMAL  AND  ARANGE

In [91]:
print(np.zeros((2,3),dtype=complex))          #Zero 2-D array
print('-------------------------------')
print(np.ones((2,3)))                         #ones 2-D array
print('-------------------------------')
print(np.empty(2))                            #empty array
print('-------------------------------')
print(np.arange(1,10,2))                      #(starting element,ending element,difference)
print('-------------------------------')
print(np.identity(3))                         #Identity Matrix
print('--------------------------------')
print(np.arange(100))
print('-------------------------------')
print(np.random.normal(size=(2, 3)))

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]
-------------------------------
[[1. 1. 1.]
 [1. 1. 1.]]
-------------------------------
[inf inf]
-------------------------------
[1 3 5 7 9]
-------------------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
-------------------------------
[[ 0.82453268  0.24126872  0.82490903]
 [ 1.53046433  0.91648177 -0.3788566 ]]


### SLICING ARRAYS

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])                        #Slice elements from index 4 to the end of the array
print('----------')
print(arr[4:])                         #Slice elements from the beginning to index 4 (not included)
print('----------')
print(arr[:4])                         #Slice from the index 3 from the end to index 1 from the end
print('----------')
print(arr[-3:-1])
print('----------')
print(arr[1:5:2]) 
print('----------')
print(arr[::2])                        #Slicing whole Array with difference 2
print('----------')

arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr1[0:2, 1:4])                  #Slicing with 2-D Array

[2 3 4 5]
----------
[5 6 7]
----------
[1 2 3 4]
----------
[5 6]
----------
[2 4]
----------
[1 3 5 7]
----------
[[2 3 4]
 [7 8 9]]


In [11]:
#RESHAPING WITH ARANGE AND LINESPACE 

print(np.arange(12).reshape(4, 3))                        #2-D array reshaping
print('---------------------------')
print(np.arange(24).reshape(2, 3, 4))                     #3-D array reshaping
print(np.linspace(0, 2, 9))                               # 9 numbers between 0 to 2



array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [27]:
##Basic Operations in NumPy

A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

print(A+B)                          #Addition
print('-------------')
print(A-B)                          #Subtraction
print('-------------')
print(A*B)                          #Multiplication
print('-------------')
print(A@B)                          #Matrix Multiplication
print('-------------')
print(A.dot(B))                     #Another way for Matrix Multiplication
print('-------------')
print(np.exp(B))                    #Exponential
print('-------------')
print(np.sqrt(B))                   #Square Root

a = np.random.rand(5)               #Creating Random Numbers
print('-------------')
b = np.arange(12).reshape(3, 4)
print(b)
print('-------------')
print(b.sum(axis=0))                #axis 0 means: rows and axis 1 means : columns
print('-------------')
print(b.sum(axis=1))
print('-------------')
print(b.min(axis=1))
print('-------------')
print(b.cumsum(axis=0))


[[3 1]
 [3 5]]
-------------
[[-1  1]
 [-3 -3]]
-------------
[[2 0]
 [0 4]]
-------------
[[5 4]
 [3 4]]
-------------
[[5 4]
 [3 4]]
-------------
[[ 7.3890561   1.        ]
 [20.08553692 54.59815003]]
-------------
[[1.41421356 0.        ]
 [1.73205081 2.        ]]
-------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------
[12 15 18 21]
-------------
[ 6 22 38]
-------------
[0 4 8]
-------------
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


### JOINING,SPLITING,SEARCHING,FILTERING AND SORTING

In [47]:
#cONCATENATION

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))            #Joining Two Arrays

print(arr)
print('---------------')

arr4 = np.array([[1, 2], [3, 4]])

arr5 = np.array([[5, 6], [7, 8]])

arr6 = np.concatenate((arr4, arr5), axis=1)    #Joining along column wise

print(arr6)

print('---------------')



#SPLITING

arr7 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])    #Spliting arrays

newarr = np.array_split(arr7, 3)                                        #Splting array into 3 parts

print(newarr)
print('----------------')

#SEARCHING

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

x = np.where(arr%2 == 0)                                  #Searching and returning output based on index number

print(x)
print('-----------------')


#SORTING

arr = np.array([0, 2, 9, 1])

print(np.sort(arr))                                       #Sorting Numbers (Ascending Order)
print('-----------------')


#FILTERING


arr = np.array([1, 36, 56, 100])

filter_arr = arr > 50                                    #Checking if it  was greater thean 42 or not and returns boolean expression

newarr = arr[filter_arr]                             

print(filter_arr)
print(newarr)


[1 2 3 4 5 6]
---------------
[[1 2 5 6]
 [3 4 7 8]]
---------------
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
----------------
(array([1, 3, 5, 7, 9], dtype=int64),)
-----------------
[0 1 2 9]
-----------------
[False False  True  True]
[ 56 100]


In [101]:
#Set Operations

#Unique
#We can use NumPy's unique() method to find unique elements from any array.
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)

print(x)
print('------------')

#Union and Intersection

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)                               #Union
newarr1 = np.intersect1d(arr1, arr2, assume_unique=True)      #Intersection

print(newarr)
print('------------')
print(newarr1)
print('------------')

#Set Difference  AND Symmetric Difference

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)
print(newarr)
print('------------')

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)



[1 2 3 4 5 6 7]
------------
[1 2 3 4 5 6]
------------
[3 4]
------------
[1 2]
------------
[1 2 5 6]


In [106]:
#Creating Functions in NumPy

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)            #frompyfunction takes 3 args : (func, input, output)
                                              #input  : number of input arrays

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))      #output : number of output arrays
print('---------------')


#ufunc means Universal functions

if type(np.add) == np.ufunc:                  #Checking Whether add is an Universal bulit in function or not
  print('add is ufunc')
else:
  print('add is not ufunc')

[6 8 10 12]
---------------
add is ufunc


In [60]:
#fromfunction and ...

#syntax :- numpy.fromfunction(function, shape, datatype)

def f(x, y):
    return 10 * x + y

a = np.fromfunction(f, (5, 4), dtype=int)                 # Creating Array with fromfunction
print(a)
print('-------------------')
print(a[0:5,1])                                           #Slicing
print('-------------------')



#Threedots (...)

#Create an 3-D array

b = np.array([[[1,2,2],
     [3,4,5]],
     [[6,7,8],
     [0,6,7]]])
# ... is same as [1, :, :]
print(b[1, ...])                                          

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
-------------------
[ 1 11 21 31 41]
-------------------
[[6 7 8]
 [0 6 7]]


In [83]:
#Linspace , Stacking  and flipping

a = np.linspace(1, 100, 5)   #Divide between numbers into 5 equal parts
print(a)

b = np.array([[[1,2,2],
     [3,4,5]],
     [[6,7,8],
     [0,6,7]]])
#Flattening array
print(b.flatten)       # Or You Can Use Ravel
#Transposing b Array
print(b.T)
print('-----------')
#Determining the Shape of The Transposed Array
print(b.T.shape)
print('-----------')

#Stacking Arrays
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,2,3],[0,5,6]])

print(np.vstack((a,b)))          #Vertical Stack (Equivalent to Row Stack)
print('------------')
print(np.hstack((a,b)))          #Horizantal Stack (Equivalent to Column Stack)
print('------------')
print(np.column_stack((a,b)))     #Column Stack
print('------------')

#Flipping

c = np.flip([1,2,3])
print(c)




[  1.    25.75  50.5   75.25 100.  ]
<built-in method flatten of numpy.ndarray object at 0x000001EB409F9F90>
[[[1 6]
  [3 0]]

 [[2 7]
  [4 6]]

 [[2 8]
  [5 7]]]
-----------
(3, 2, 2)
-----------
[[1 2 3]
 [4 5 6]
 [3 2 3]
 [0 5 6]]
------------
[[1 2 3 3 2 3]
 [4 5 6 0 5 6]]
------------
[[1 2 3 3 2 3]
 [4 5 6 0 5 6]]
------------
[3 2 1]


In [87]:
# Saving and Loading Files 

a = np.array([1, 2, 3, 4, 5, 6])
np.save('filename', a)                    #You Can Save Files Like This

a = np.load('filename.npy')               #You Can Load Files

# You Can Load csv or any other files with their extension
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.savetxt('new_file.csv', csv_arr)       #Saving csv files 
np.loadtxt('new_file.csv')                #Loading csv files

array([1., 2., 3., 4., 5., 6., 7., 8.])